# This file is rendered via JSON-e by
# - mozilla-taskcluster - https://docs.taskcluster.net/reference/integrations/mozilla-taskcluster/docs/taskcluster-yml
# - cron tasks - taskcluster/taskgraph/cron/decision.py
# - action tasks - taskcluster/taskgraph/actions/registry.py
---
version: 1
reporting: checks-v1
policy:
  pullRequests: public
tasks:
  $let:
    owner: taskcluster-internal@mozilla.com

    # This only supports pushes and pull requests for now.
    # If we start responding to another action type, make this
    # a $match.
    repo:
      $if: 'tasks_for == "github-push"'
      then:
        git_url: ${event.repository.url}
        url: ${event.repository.url}
        ref: ${event.after}
      else:
        git_url: ${event.pull_request.head.repo.git_url}
        url: ${event.pull_request.head.repo.url}
        ref: ${event.pull_request.head.sha}
  in:
    $let:
      tests:
        - image: 'python:3.6'
          name: python:3.6 tests
          command:
            - /bin/bash
            - '--login'
            - '-c'
            - >-
              git clone ${repo.git_url} repo &&
              cd repo &&
              git config advice.detachedHead false &&
              git checkout ${repo.ref} &&
              pip install --no-use-pep517 -e . &&
              python setup.py test
        - image: 'python:3.6'
          name: flake
          command:
            - /bin/bash
            - '--login'
            - '-c'
            - >-
              git clone ${repo.git_url} repo &&
              cd repo &&
              git config advice.detachedHead false &&
              git checkout ${repo.ref} &&
              pip install --no-use-pep517 -e . flake8 &&
              flake8 tcadmin
        - image: 'python:3.6'
          name: black
          command:
            - /bin/bash
            - '--login'
            - '-c'
            - >-
              git clone ${repo.git_url} repo &&
              cd repo &&
              git config advice.detachedHead false &&
              git checkout ${repo.ref} &&
              pip install --no-use-pep517 -e . black &&
              black --check tcadmin
    in:
      $let:
        test_tasks:
          $map: {$eval: tests}
          each(test):
            taskId: {$eval: as_slugid(test.name)}
            provisionerId: aws-provisioner-v1
            workerType: github-worker
            created: {$fromNow: ''}
            deadline: {$fromNow: '60 minutes'}
            payload:
              maxRunTime: 3600
              image: ${test.image}
              command: {$eval: 'test.command'}
              env:
                NO_TEST_SKIP: "1"
            metadata:
              name: ${test.name}
              description: ${test.name}
              owner: ${owner}
              source: ${repo.url}

      in:
        $flattenDeep:
        - $if: 'tasks_for == "github-push"'
          then:
            - {$eval: test_tasks}
        - $if: 'tasks_for == "github-pull-request" && event["action"] in ["opened", "reopened", "synchronize"]'
          then:
            # We can skip this if pushed to our own repo since push event will get it
            $if: 'event.pull_request.base.repo.id != event.pull_request.head.repo.id'
            then: {$eval: test_tasks}
